# Generated by Django 4.2.6 on 2023-10-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(blank=True, db_column='house_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_request_set', to='account.house')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownership_request_set', to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorityRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('house', models.ForeignKey(blank=True, db_column='house_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_request_set', to='account.house')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_request_set', to='account.user')),
            ],
        ),
    ]
