# Generated by Django 4.2.6 on 2023-10-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_ownershiprequest_authorityrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
